gfskMod = comm.CPMModulator( ...
    'ModulationOrder',2, ...
    'FrequencyPulse','Gaussian', ...
    'BandwidthTimeProduct',0.5, ...
    'ModulationIndex',1, ...
    'BitInput',true);
filetext=fileread('mensaje_hamming.txt')
filetext = strrep(filetext, '[', ''); % Elimina el paréntesis cuadrado izquierdo
filetext = strrep(filetext, ']', '')
filetext=str2num(filetext);
size(filetext)
tic();
y = gfskMod(filetext');
tiempo=toc()
csvwrite('modulado.txt',y)